### ISSUE TITLE
Can I encode a javascript object?

### ISSUE THREAD

**Issue by coodoo** [capnp-js/serialization#16]
Could I do something like this?

```javascript
var obj = {foo: 123, bar: [456, 789]};
var result = capnp.encode( obj );
```

Thanks.

**Comment by popham** [comment]
Short answer: No.  I recall that Kenton Varda's js implementation (node only) does something like this.

Anything that does this I would describe as too magical for my taste, i.e. are your numbers Int16, UInt16, Float32, UInt64, ...?  This implementation will always be schema driven :(.
