### ISSUE TITLE
Code generation with syntax errors

### ISSUE THREAD

**Issue by sirudog** [capnp-js/serialization#17]
I have issues with the generated js code based on even very simple schemas like this:
@0xec2f2fe5874ad874;
using Uid=Int32;
struct User {
    id @0 :Uid;
    name @1 :Text;
}

I have already opened this issue and detailed the steps I did before I got the error here: https://github.com/capnp-js/plugin/issues/6
I thought it would be more visible if I report it here, too, and hopefully it can be solved by someone's help

**Comment by popham** [comment]
Sorry for the neglect.  I'm currently working on a migration to ES6 modules combined with [Flow](https://flowtype.org), so I get disoriented when I touch this code.  Give me a few weeks to bump all of this stuff.

**Comment by msackman** [comment]
Don't mean to pester, but was just wondering how this work is coming along? Would just be useful to know from the pov of scheduling my own work and projects.

**Comment by sirudog** [comment]
I guess I can close this issue after almost two years has passed without new info about this refactor mentioned by @popham. There is a new project filling the gap if anyone is trying to use capnproto in js/ts: https://github.com/jdiaz5513/capnp-ts
Hope this helps
